### ISSUE TITLE
abcde-musicbrainz-tool failed to run; ABORT

### ISSUE THREAD

**Issue by sappha58** [johnlane/abcde#10]
I'm wanting to rip my music CDs, and found abcde.  I like it a lot, and now I learn that I can add album art to it!  Wonderful!

I've hit a few bumps in the road, but this one I can't figure out.  My system info is:

Linux intrepid 3.13.0-168-generic #218-Ubuntu
  SMP Thu Mar 14 16:56:08 UTC
  2019 x86_64 x86_64 x86_64 GNU/Linux

When I try to run abcde, I use the command line:
abcde -d /dev/sr0 -c /home/sappha58/.abcde-albumart.conf -p -x -o mp3

I am using Andrew Strong's config file to do it.  For brevity, here's the last bit of the log file I got using -D 2>&1 | tee abcde.log:

++ echo 'Y1MqTFR_zUvb6EiIYS9Tni7.ytI- 8 150 21535 44304 79377 92903 112507 131387 148480 2268'
+ MBDISCID=Y1MqTFR_zUvb6EiIYS9Tni7.ytI-
+ local SOURCE_WORKDIR=/home/music-new/abcde.6b08d808/data-musicbrainz
+ mkdir -p /home/music-new/abcde.6b08d808/data-musicbrainz
+ abcde-musicbrainz-tool --command data --discid Y1MqTFR_zUvb6EiIYS9Tni7.ytI- --workdir /home/music-new/abcde.6b08d808/data-musicbrainz --start 0
Can't locate object method "result" via package "Mojo::Transaction::HTTP" at /usr/local/share/perl/5.18.2/WebService/MusicBrainz/Request.pm line 69.
+ error=255
+ '[' 255 '!=' 0 ']'
+ log error 'abcde-musicbrainz-tool failed to run; ABORT'
+ BLURB=error
+ shift
+ case $BLURB in
+ echo '[ERROR] abcde: abcde-musicbrainz-tool failed to run; ABORT'
[ERROR] abcde: abcde-musicbrainz-tool failed to run; ABORT
+ exit 255

Can someone aim me in the right direction, please?

**Comment by sappha58** [comment]
More info on abcde that I'm using:

This is abcde v2.9

use WebService::MusicBrainz 1.0.4;

**Comment by johnlane** [comment]
Hello, you should ask this on the main repo at https://git.einval.com/cgi-bin/gitweb.cgi?p=abcde.git or see the web site https://abcde.einval.com where there is a bug tracker. This is just my own copy of the repo and I haven't used it for ages.
