### ISSUE TITLE
Output folder

### ISSUE THREAD

**Issue by davidwallis3101** [johnlane/abcde#11]
Hi,

My music is currently arranged by artist under folders matching the alphabet, IE 

Adele's albums would be under

/mnt/music/a/adele

and The Beautiful South would go under:

/mnt/music/b/Beautiful South, The

is this sort of thing possible?

(its also dropping everything in a folder which is the file type which I haven't managed to sort yet..

/mnt/music/mp3/adele 

Thanks

David

**Comment by johnlane** [comment]
Hello. This is a patched version of abcde. You should check out https://abcde.einval.com and probably raise your query there.
