### ISSUE TITLE
do_embedalbumart - wont't work if there are more output formats

### ISSUE THREAD

**Issue by fs101299** [johnlane/abcde#12]
Hello,

the do_embedalbumart() works only, if there is one output format.
If you select two ones, e.g. OUTPUTTYPE="flac,mp3"  then the second one doesn't get the embedded albumart. because there are these two lines at each Formattype, so the second won't find the album, because it is moved to $FINALDIR"/albumart_backup.

I 've marked these two lines, so the album art will stay in the musicfolder, and it works fine.
#mkdir "$FINALDIR"/albumart_backup
#mv "$ALBUMARTFILE" "$FINALDIR"/albumart_backup

**Comment by johnlane** [comment]
Hello. This is a patched version of abcde. You should check out https://abcde.einval.com and probably raise your query there.
