### ISSUE TITLE
FAILED: $ abcde -o flac -L -n

### ISSUE THREAD

**Issue by SzykCech4** [johnlane/abcde#13]
Helo!
I use your abcde to rip my small CD collection in order to play them in my computer. But I have some locally published (== rare) CD without CDDB info record. So I try command like this:
`$ abcde -o flac -L -n`
But I got:
```
Grabbing entire CD - tracks:  001 002 003 004 005 006 007 008 009 010 011 012 013 014 015 016
Can't use an undefined value as an ARRAY reference at /usr/local/bin/abcde-musicbrainz-tool line 92.
[ERROR] abcde: abcde-musicbrainz-tool failed to run; ABORT
```
NOTE: I successfully ripped few CD which exists in CDDB. Only unknown CD failed to rip.
My system is KaOS roling release.

uname -a
Linux optiplex-760 5.3.8-1 #1 SMP PREEMPT Tue Oct 29 09:55:07 UTC 2019 x86_64 GNU/Linux

My system config is:
[system.txt](https://github.com/johnlane/abcde/files/3825622/system.txt)

My /etc/abcde.conf is:
[abcde.conf.zip](https://github.com/johnlane/abcde/files/3825598/abcde.conf.zip)

**Comment by johnlane** [comment]
Hello. This is a patched version of abcde. You should check out https://abcde.einval.com and probably raise your query there.
