### ISSUE TITLE
How to update musicbrainz webservice dependency?

### ISSUE THREAD

**Issue by niels-anders** [johnlane/abcde#14]
Hi there,

first of all, thanks for making abcde!

I run into an issue with musicbrainz. The abcde binaries of the ubuntu 18.04 repositories are quite out of date (2.8.1) and musicbrainz gives an 410 error there. So I downloaded the latest abcde 2.9.3 but running `abcde -o flac` fails with :

```
[ERROR] abcde: abcde-musicbrainz-tool failed to run; ABORT
```
running `abcde-musicbrainz-tool` explicitly I get:

```
WebService::MusicBrainz version v1.0.4 required--this is only version v0.930.0 at ./abcde-musicbrainz-tool line 19.
```

So I guess need to upgrade the musicbrainz libary. Do you have any suggestions on how to do this?

I tried compiling the perl scripts from https://metacpan.org/release/WebService-MusicBrainz but run into dependency issues and I don't have experience with compiling perl.

**Comment by johnlane** [comment]
Hello, I didn't make abcde, I just patched it with some additions some time ago. You should check out https://abcde.einval.com and probably raise your query there.
