### ISSUE TITLE
Musicbrainz Error Code 400

### ISSUE THREAD

**Issue by Nitesedge** [johnlane/abcde#2]
Every rip receives this response from MusicBrainz: Code: 400 Error: Bad Request

Full Text (discid replaced with XX):

```
Trying CDDB method cddb.
Checking CDDB server status...
Querying the CDDB server...
Obtaining CDDB results...
Unable to find a match with cddb, moving on to the next option.
Trying CDDB method musicbrainz.
Obtaining Musicbrainz results...
URL (http://musicbrainz.org/ws/1/release/?type=xml&discid=XXXXXXX) Request Failed - Code: 400 Error: Bad Request
Unable to find a match with musicbrainz, generating CDDB template.
No CDDB information found, trying cdtext from the CD
No Musicbrainz match.
```

Tested against 2.8.1 and git clone of current repo

**Comment by johnlane** [comment]
This probably doesn't help but I get output like this:
```
Getting CD track info... Grabbing entire CD - tracks:  01 02 03
Found 0 matches so far
Trying lookup method musicbrainz
Obtaining Musicbrainz results...
Found 1 matches so far
Trying lookup method cddb
Checking CDDB server status...
Querying the CDDB server...
Obtaining CDDB results...
Retrieved 2 matches...
```
As a real example, using discid `KiGaFKO_GmpnVQYT5Z8wUmT_zH8-` with the URL in your output, I get an XML document returned. If you can supply the `XXXXX` in your example I could test it. Does this work for you:

```
$ curl 'http://musicbrainz.org/ws/1/release/?type=xml&discid=KiGaFKO_GmpnVQYT5Z8wUmT_zH8-'
```
My config (`~/.abcde.conf`) contains
```
CDDBMETHOD=musicbrainz,cddb
```

I am running  my patched version of 2.9.1. I use Arch Linux and I have installed packages

* perl-webservice-musicbrainz 1.0.4-1
* perl-musicbrainz-discid 0.04-1

I'll help if I can but you might be better asking on the [abcde mailing list](https://lists.einval.com/cgi-bin/mailman/listinfo/abcde-users).

**Comment by macrophone** [comment]
I've got an error 410 with abcde package on Debian 9 (2.8.1-1-all) with every rip : 

`Grabbing entire CD - tracks: 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21
URL (http://musicbrainz.org/ws/1/release/?type=xml&discid=U8xIqp7Af7gvHUl4R_oG0oBF970-) Request Failed - Code: 410 Error: Gone
No Musicbrainz match.
`

cddb method works like a charm.

**Comment by reitzig** [comment]
Putting that URL in a browser yields

> https://blog.metabrainz.org/2018/02/01/web-service-ver-1-0-ws-1-will-be-removed-in-6-months/

'Nuff said.
