### ISSUE TITLE
abcde documentation should point to CDDB file format description

### ISSUE THREAD

**Issue by kermitfrog** [johnlane/abcde#4]
I just had to edit some cddb data before ripping and wasn't sure how to do that right.. 
so i spent about 30 minutes searching for information on the syntax until i found in a file called "DBFORMAT" inside the source archive of cddbd. Not the easiest find...

Since this is the format abcde uses to edit tag data, i think its documentation should at least tell the user where to find that information.

**Comment by johnlane** [comment]
Please would you raise issues with the baseline [abcde](https://abcde.einval.com) application on [their bugtracker](https://abcde.einval.com/bugzilla).
