### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by foxsam21** [johnlane/abcde#5]
Sometimes it would be convenient to pre-fill a template to make it easier to do non-interactive ripping. I am proposing that we have a way to fill out a template that when abcde creates a template it can grab the info from that template.
For example:
~ $ abcde --template ~/newest_hit.txt

in ~/newest_hit.txt are lines such as:

DTITLE=Newsest Hit / ME!
DYEAR=2018
DGENRE=jazz
TTITLE0= First track
TTITLE1= Best Track

etc... Whatever is missing will be filled in as usual by default

**Comment by johnlane** [comment]
Hello. This is a patched version of abcde. You should check out https://abcde.einval.com and probably raise your query there.
