### ISSUE TITLE
Track Number Interpreted as Octal

### ISSUE THREAD

**Issue by aiudirog** [johnlane/abcde#7]
While ripping audio books and specifying where to start counting the track numbers based upon the track count from the previous CD, I found that bash errors when reading certain tracks. After some investigation, I found that when using the -t option to specify the starting track number, $UTRACKNUM is front filled with zeros. This causes some issues on line [466](https://github.com/johnlane/abcde/blob/master/abcde#L466) when tracks 8 and 9 are read. Since $UTRACKNUM is 008 and 009 in these scenarios, bash interprets them as octal values, which causes the script to error and produce the wrong numbers for the following tracks. I fixed the issue by simply forcing the value to be interpreted as a decimal value. I'm not sure if this is the best solution or backwards compatible, as bash isn't my best language, but it solves the problem for me. I am running bash v4.4.23 and abcde v2.9.1 on Arch Linux. Below I have included my fix:

Original:
```
TRACKNUM=$( printf %0."${CURRENTTRACKPADDING}"d $(("${UTRACKNUM}" + "${STARTTRACKNUMBER}" - "${FIRSTTRACK}")))
```

Patched:
```
UTRACKNUM_DEC=$((10#$UTRACKNUM))
TRACKNUM=$( printf %0."${CURRENTTRACKPADDING}"d $(("${UTRACKNUM_DEC}" + "${STARTTRACKNUMBER}" - "${FIRSTTRACK}")))
```

**Comment by johnlane** [comment]
Hello. This is a patched version of abcde. You should check out https://abcde.einval.com and probably raise your query there.
