### ISSUE TITLE
Fuller tagging from Musicbrainz

### ISSUE THREAD

**Issue by mfeif** [johnlane/abcde#8]
When one uses a tool like Picard, there is a rich set of tags that result.

When one uses Musicbrainz option via abcde, you just get DiscId and artist/title for tracks.

Since the discs are properly identified, is there a reason we can't get the rest of the data?

As-is, I need to rip/encode, then move the files to a machine with a GUI (from a home file server) so I can actually get the nice tags from Picard.

Thanks!

**Comment by johnlane** [comment]
Hello. This is a patched version of abcde. You should check out https://abcde.einval.com and probably raise your query there.
