### ISSUE TITLE
glyrc is not avail for freebsd

### ISSUE THREAD

**Issue by gearhead** [johnlane/abcde#9]
First: Thanks for keeping this alive. Great tool!

Second: I am using this on my NAS running freenas. I have version 2.9.2 installed, but cannot install glyrc. No port exists that I can find nor is it a compiled package. If I try to build it from source, It fails with a linker command issue. Is there another option other than glyrc for getting the album art? Currently use this to get the rip then use misicbrainz picard on another machine to get the album art.

**Comment by johnlane** [comment]
Hi, there have been enhancements made that surpass what I did for album art. You should check out https://abcde.einval.com to see if that helps.
